### ISSUE TITLE
verification fails when list is added to target json

### ISSUE THREAD

**Issue by kamranalam81** [Gnof/JsonValidator#1]
code breaks when list of values are included in the target json. If there is no list then it works fine

for example:
{
    "version": "4.2",
    "dictionary": {
        "products": [{
            "id": "xyz",
            "features": ["feature1.xyz",
            "feature2.xyz"],
            "name": {
                "en": "test"
            },
            "description": {
                "en": "test product description"
            },
            "grace_period": 30,
            "admin_block_period": 30,
            "user_block_period": 30
        }]
    }
}
verification:
{attribute:"en", value:"test product description"} or
{attribute:"features", value:["feature1.xyz"]}

**Comment by Gnof** [comment]
Looking into it now :)
-- Can you give me the error it returns?

**Comment by kamranalam81** [comment]
Thanks for looking into this.

An error is thrown:
java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
    at com.gnof.core.ValidationWorker.gatherObjectDataHelper(ValidationWorker.java:623)
    at com.gnof.core.ValidationWorker.gatherObjectDataHelper(ValidationWorker.java:623)
    at com.gnof.core.ValidationWorker.gatherObjectDataHelper(ValidationWorker.java:620)
    at com.gnof.core.ValidationWorker.gatherObjectData(ValidationWorker.java:578)
    at com.gnof.core.ValidationWorker.validate(ValidationWorker.java:104)
    at com.gnof.core.JsonValidator.validate(JsonValidator.java:178)
    at com.gnof.core.JsonValidator.validate(JsonValidator.java:138)

**Comment by Gnof** [comment]
Sorry for the delay. I've committed 0ff63fe853bfe61ac758b4b38cdcda5eb635f5bb which should address the issues.
I've also included unit tests that show the scenario documented working as expected.

Feel free to pull the repo and update the library in your project to get the fix, and let me know if it's working for you.

**Comment by kamranalam81** [comment]
Thanks Kory for looking into this. There are few more issues uncovered , i'll post them tomorrow.

**Comment by kamranalam81** [comment]
there are issues associated to ancestor validation. "java.lang.IllegalStateException is thrown"
I have added below three more tests to the BugFixTest.java

```
@Before
    public void setUp() throws Exception {
                ...
                ...     
kamranBug1Validation3= "{attribute:\"en\",value:\"test\", ancestor:[\"name\",\"products\"]}";

kamranBug1Validation4= "{attribute:\"en\",value:\"test\", ancestor:\"name\"}";

kamranBug1Validation5= "{attribute:\"features\",value:\"feature2.xyz\", ancestor:\"products\"}";
    }
```

```
@Test
public void testBug1() {
    JsonValidator jv = new JsonValidator();
    ...
            ...
    boolean thirdResult = jv.validate(kamranBug1Validation3, kamranBug1Json);
    assertTrue(thirdResult);
    boolean fourthResult = jv.validate(kamranBug1Validation4, kamranBug1Json);
    assertTrue(fourthResult);
    boolean fifthResult = jv.validate(kamranBug1Validation5, kamranBug1Json);
    assertTrue(fifthResult);
}
```

`They are failing for java.lang.IllegalStateException
    at com.google.gson.JsonArray.getAsString(JsonArray.java:124)
    at com.gnof.core.ValidationUnit.<init>(ValidationUnit.java:165)
    at com.gnof.core.JsonValidator.validate(JsonValidator.java:179)
    at com.gnof.core.JsonValidator.validate(JsonValidator.java:141)
    at com.gnof.test.BugFixTest.testBug1(BugFixTest.java:72)`

**Comment by Gnof** [comment]
I'll get those addressed shortly, looks like it's a similar issue, but under a different validation paradigm (so it should be an easy fix)

**Comment by kamranalam81** [comment]
[sampleJson.txt](https://github.com/Gnof/JsonValidator/files/198524/sampleJson.txt)

There are issues with handling list / array.  Could you please use the attached sample json for test and retrieve different sections using ancestor or composite.

Fail:
1.value [... , ...] 
2.ancestor [... , ...] -- fail
3. composite
 eg:  {attribute:"features",value:"feature1.Great.service.com",composite: {attribute:"features", ancestor:"products"}}

Could you give an example of how to validate two attributes and values in one query.
something like: {{attribute1: "", value""} , {attribute2: "", value""}}

Thank you so much for quick fix
